{% set name = "fps-auth-fief" %}
{% set version = "0.0.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth_fief-{{ version }}.tar.gz
  sha256: d10f30b921b81c5a2f4f2067670f47b3bf035aa3bb79e0917a28850c56bd5a57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<1
    - fief-client-fastapi

test:
  imports:
    - fps_auth_fief
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_fief
  summary: An FPS plugin for the authentication API, using Fief
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_fief
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
