{% set name = "fps-auth-fief" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth_fief-{{ version }}.tar.gz
  sha256: a61d95a96a317ff5210612b0cd77e25bd623e038131aecdbe362dcab427c312a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - fief-client-fastapi

test:
  imports:
    - fps_auth_fief

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_fief
  summary: An FPS plugin for the authentication API, using Fief
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_fief
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
