schema_version: 1

context:
  version: "0.10.1"

package:
  name: fps-auth-fief
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-auth-fief/fps_auth_fief-${{ version }}.tar.gz
    sha256: f4260258602a701132fda3a16532aff7a9b55de822168e3da4fd98f4cdea17d1

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0
    - fief-client-fastapi

tests:
  - python:
      imports: fps_auth_fief
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth_fief
  summary: An FPS plugin for the authentication API, using Fief.

extra:
  recipe-maintainers:
    - davidbrochart
